config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => "sessions#new"
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "/dashboard" => "home#index", as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all

  end

  # GET /users/new
  def new
    @user = User.new
    @user_id = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
     
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:First_name,:Last_name,:role,:age,:date_of_joining,:Salary_per_annum,:Salary_per_month,:address,:Mobile,:Blood_type,:Emergency_contact_name,:Emergency_contact_number,:Primary_skill,:Secondary_skill1,:Secondary_skill2,:Notice_period_in_days,:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<%= stylesheet_link_tag "index" %>
</head>
<body >
	<br><br><br> 
	<h1 style="background-color: initial;">welcome</h1>
	
	     <%= current_user.First_name %>  
	 <%if %>
	
		<% if current_user.role == "Admin" %>

				&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <button > <%= link_to "Registration", signup_path %><br><br></button>
				<button ><%= link_to "view Employee", users_path%><br><br></button>

 

 <%elsif current_user.role == "Employee"%>
 	
 	

 	<table border="1"  id="table">
 		<tr>
 			<th>name</th>

 			<td><%= current_user.First_name%></td>
 		</tr>
 		<tr>
 			<th>last name</th>
 			<td><%= current_user.Last_name%></td>
 		</tr>
 		<tr>
 			<th>age</th>
 			<td><%= current_user.age%></td>	
 		</tr>
 		<tr>
 			<th>date_of_joining</th>
 			<td><%= current_user.date_of_joining%></td>
 		</tr>
 		<tr>
 			<th>Salary_per_annum</th>
 			<td><%= current_user.Salary_per_annum%></td>
 		</tr>
 		<tr>
 			<th>Salary_per_month</th>
 			<td><%= current_user.Salary_per_month%></td>
 		</tr>
 		<tr>
 			<th>email</th>
 			<td><%= current_user.email%></td>
 		</tr>
 		<tr>
 			<th>address</th>
 			<td><%= current_user.address%></td>
 		</tr>
 		<tr>
 			<th>Mobile</th>
 			<td><%= current_user.Mobile%></td>
 		</tr>
 		<tr>
 			<th>Blood_type</th>
 			<td><%= current_user.Blood_type%></td>
 		</tr>
 		<tr>
 			<th>Emergency_contact_name</th>
 			<td><%= current_user.Emergency_contact_name%></td>
 		</tr>
 		<tr>
 			<th>Emergency_contact_number</th>
 			<td><%= current_user.Emergency_contact_number%></td>
 		</tr>
 		<tr>
 			<th>Primary_skill</th>
 			<td><%= current_user.Primary_skill%></td>
 		</tr>
 		<tr>
 			<th>Secondary_skill1</th>
 			<td><%= current_user.Secondary_skill1%></td>
 		</tr>
 		<tr>
 			<th>Secondary_skill2</th>
 			<td><%= current_user.Secondary_skill2%></td>
 		</tr>
 
	</table>


	<%end%>
 
    		<div class="content"> 
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
				<button id="myBtn"><%= link_to "Log Out",logout_path %> </button>

 					 <!-- Use a button to pause/play the video with JavaScript -->
  				
			</div>
 
    		
    
     
    	

	<% else %>
    	<%= redirect_to login_path%>
	<% end %>
	

<video autoplay muted loop id="myVideo">
  <source src="/assets/background.mp4" type="video/mp4">
</video>

<!-- Optional: some overlay text to describe the video -->






<!-- javsscrit for the video -->
<script>
// Get the video
var video = document.getElementById("myVideo");

// Get the button
var btn = document.getElementById("myBtn");

// Pause and play the video, and change the button text
function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>



<p id=”notice”><%= notice %></p>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
<head>
 
  <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
   <%= stylesheet_link_tag "form" %>

  <title></title>
</head>
<body>


  <%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<table id="customers">
  <tr>
    <td>
      <%= form.label :First_name %>
    </td>
    <td>
      <%= form.text_field :First_name %>
    </td>
  </tr>
 <tr>
    <td>
      <%= form.label :Last_name %>
    </td>
    <td>
      <%= form.text_field :Last_name %>
    </td>
  </tr>

 <tr>
    <td>
      <%= form.label :age %>
    </td>
    <td>
      <%= form.number_field :age %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :date_of_joining %>
    </td>
    <td>
      <%= form.datetime_field :date_of_joining %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Salary_per_annum %>
    </td>
    <td>
      <%= form.number_field :Salary_per_annum %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Salary_per_month %>
    </td>
    <td>
      <%= form.number_field :Salary_per_month %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :email %>
    </td>
    <td>
      <%= form.text_field :email %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :password %>
    </td>
    <td>
      <%= form.password_field :password %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :password_confirmation %>
    </td>
    <td>
      <%= form.password_field :password_confirmation %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :address %>
    </td>
    <td>
      <%= form.text_field :address %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Mobile %>
    </td>
    <td>
      <%= form.number_field :Mobile %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Blood_type %>
    </td>
    <td>
      <%= form.text_field :Blood_type %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Emergency_contact_name %>
    </td>
    <td>
      <%= form.text_field :Emergency_contact_name %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Emergency_contact_number %>
    </td>
    <td>
       <%= form.number_field :Emergency_contact_number %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Primary_skill %>
    </td>
    <td>
      <%= form.text_field :Primary_skill %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Secondary_skill1 %>
    </td>
    <td>
      <%= form.text_field :Secondary_skill1 %>
    </td>
  </tr>
   <tr>
    <td>
      <%= form.label :Secondary_skill2 %>
    </td>
    <td>
      <%= form.text_field :Secondary_skill2 %>
    </td>
  </tr>
  <tr>
    <td>
      <%= form.label :role %>
    </td>
    <td>
              <%#= form.collection_select :role, [Provider.order(:name)],:id,:name, include_blank: true %>
          <%= form.select :role, ['Admin', 'Employee']%>
    </td>
  </tr>
    <tr>
    <td>
      <%= form.label :Notice_period_in_days %>
    </td>
    <td>
      <%= form.number_field :Notice_period_in_days %>
    </td>
  </tr>

<tr>
  <td>
      <div class="actions">
      <%= form.submit %>
    </div>

  </td>

<% end %>

</tr>
</table>




</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag "employee_details" %>

  <title></title>
</head>
<body  style="background-color:  ">

<p id="notice"><%= notice %></p>

<h1 style="background-color: lightgray ; ">Users</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button><%= link_to 'New', new_user_path %></button>

  <button type="button">
    <%= link_to 'Back', dashboard_path %>
  </button>

</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= stylesheet_link_tag "form" %>
	<title></title>
</head>
<body>
	<h1 style="padding: 30px;text-align: center;color: black;font-size: 30px;background-color: #D3D3D3">Employee Registration Form</h1>

	<%= render 'form', user: @user %>
	<button type="button">
		<%= link_to 'Back', dashboard_path %>
	</button>
	
	
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= stylesheet_link_tag "show" %>
	<title>
		
	</title>
</head>
<body>

	<p id="notice"><%= notice %></p>
<h2>
		<%= @user.First_name %>

</h2>
<br>
<table>
	<tr>
		<td>
			  <strong>First_name:</strong>
			  <%= @user.First_name %>
		</td>
		<td>
			  <strong>Last_name:</strong>
			  <%= @user.Last_name %>
		</td>
	</tr>
	<tr>
		<td>
  				<strong>age:</strong>
 				 <%= @user.age %>
		</td>
		<td>
			<strong>date_of_joining:</strong>
			<%= @user.date_of_joining %>
		</td>
	</tr>
	<tr>
		<td>
			<strong>Salary_per_annum:</strong>
			<%= @user.Salary_per_annum %>
		</td>
		<td>
			<strong>Salary_per_month:</strong>
			<%= @user.Salary_per_annum %>
		</td>

	</tr>
	<tr>
		<td>
			<strong>email:</strong>
			<%= @user.email %>
		</td>
		<td>
			<strong>address:</strong>
			<%= @user.address %>
		</td>
	</tr>
	<tr>
		<td>
			<strong>Emergency_contact_name:</strong>
			<%= @user.Emergency_contact_name %>
		</td>
		<td>
			<strong>Emergency_contact_number:</strong>
			<%= @user.Emergency_contact_number %>
		</td>
		
	</tr>
		<tr>
		<td>
			<strong>Mobile:</strong>
			<%= @user.Mobile %>
		</td>
		<td>
			<strong>Blood_type:</strong>
			<%= @user.Blood_type %>
		</td>
	</tr>
	<tr>
		<td>
			<strong>Primary_skill:</strong>
			<%= @user.Primary_skill %>
		</td>
		<td>
			<strong>Secondary_skill1:</strong>
			<%= @user.Secondary_skill1 %>
		</td>
	</tr>
	<tr>
		<td>
			<strong>Secondary_skill2:</strong>
			<%= @user.Secondary_skill2 %>
		</td>
		<td>
			<strong>Notice_period_in_days:</strong>
			<%= @user.Notice_period_in_days %>
		</td>
	</tr>
	<tr>
		<td>
			<strong>Job role:</strong>
			<%= @user.role %>
		</td>

	</tr>



</table>
<p>
   
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</body>
</html>